In [109]:
import pandas as pd

In [111]:
import numpy as np

In [113]:
import warnings as w

In [127]:
w.filterwarnings("ignore")

In [137]:
df_table1=pd.read_excel(r"C:\DataBase\Campaign data.xlsx")

In [142]:
df

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [144]:
df.columns

Index(['Date', 'Data source', 'Campaign', 'Media Type', 'City', 'Metric',
       'Value'],
      dtype='object')

In [146]:
df.shape

(123699, 7)

In [148]:
df.head()

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.0
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.0

In [150]:
df.tail()

,Date,Data source,Campaign,Media Type,City,Metric,Value
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [152]:
df.sample()

,Date,Data source,Campaign,Media Type,City,Metric,Value
61267,2021-01-29,Snapchat,Rogue campaign 4,Online Video,Salt Lake City,Media Cost,41.41

In [154]:
df.dtypes

Date           datetime64[ns]
Data source            object
Campaign               object
Media Type             object
City                   object
Metric                 object
Value                 float64
dtype: object

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123699 entries, 0 to 123698
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Date         123699 non-null  datetime64[ns]
 1   Data source  123699 non-null  object
 2   Campaign     123699 non-null  object
 3   Media Type   123699 non-null  object
 4   City         123699 non-null  object
 5   Metric       123699 non-null  object
 6   Value        123699 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 6.6+ MB

In [158]:
df.describe()

                                Date         Value
count                         123699  1.236990e+05
mean   2021-02-09 21:36:27.868940032  6.973219e+03
min              2019-12-30 00:00:00  0.000000e+00
25%              2020-10-21 00:00:00  6.000000e+00
50%              2021-02-01 00:00:00  7.536000e+01
75%              2021-08-04 00:00:00  1.144900e+03
max              2021-09-30 00:00:00  1.627800e+06
std                              NaN  3.400261e+04

In [160]:
print("no of rows:", df.shape[0])

no of rows: 123699

In [162]:
print("no of columns:", df.shape[1])

no of columns: 7

In [164]:
df_table1

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [166]:
 df_table2 = pd.read_excel(r"C:\DataBase\Campaign data.xlsx", sheet_name = "Table 2")

In [168]:
df_table2

                 Campaign   Message type        Model
0       Sentra campaign 2  Future Market       Sentra
1       Sentra campaign 4  Future Market       Sentra
2       Sentra campaign 3  Future Market       Sentra
3       Sentra campaign 1  Future Market       Sentra
4       Altima campaign 1  Future Market       Altima
5       Altima campaign 5  Future Market       Altima
6       Altima campaign 4  Future Market       Altima
7       Altima campaign 6  Future Market       Altima
8        Kicks campaign 6  Future Market        Kicks
9        Kicks campaign 5  Future Market        Kicks
10       Rogue campaign 1  Future Market        Rogue
11       Rogue campaign 3  Future Market        Rogue
12       Rogue pre launch  Future Market        Rogue
13       Rogue campaign 5  Future Market        Rogue
14       Rogue campaign 4  Future Market        Rogue
15  Pathfinder campaign 3    Near Market   Pathfinder
16      Armada campaign 1    Near Market       Armada
17  Pathfinder campaign 8    Near Market   Pathfinder
18  Pathfinder campaign 5    Near Market   Pathfinder
19  Pathfinder campaign 6    Near Market   Pathfinder
20  Pathfinder campaign 7    Near Market   Pathfinder
21      Altima campaign 3  Future Market       Altima
22      Altima campaign 2  Future Market       Altima
23      Altima campaign 7    Near Market       Altima
24      Altima campaign 8    Near Market       Altima
25       Rogue campaign 2  Future Market        Rogue
26       Kicks campaign 3  Future Market        Kicks
27       Kicks campaign 4  Future Market        Kicks
28  Pathfinder campaign 2    Near Market   Pathfinder
29  Pathfinder campaign 1    Near Market   Pathfinder
30  Pathfinder campaign 4    Near Market   Pathfinder
31           shop at home  Future Market  Multi-Model
32       Kicks campaign 2    Near Market        Kicks
33       Kicks campaign 1    Near Market        Kicks
34      Armada campaign 2    Near Market       Armada
35      Armada campaign 4    Near Market       Armada
36      Armada campaign 3    Near Market       Armada
37     Sentra campaign 11    Near Market       Sentra
38     Sentra campaign 14    Near Market       Sentra
39     Sentra campaign 20    Near Market       Sentra
40     Sentra campaign 21    Near Market       Sentra
41      Sentra campaign 9    Near Market       Sentra
42      Sentra campaign 7    Near Market       Sentra
43      Sentra campaign 6    Near Market       Sentra
44     Sentra campaign 12    Near Market       Sentra
45     Sentra campaign 19    Near Market       Sentra
46     Sentra campaign 18    Near Market       Sentra
47     Sentra campaign 22    Near Market       Sentra
48     Sentra campaign 23    Near Market       Sentra
49     Sentra campaign 25    Near Market       Sentra
50      Sentra campaign 5    Near Market       Sentra
51     Sentra campaign 13    Near Market       Sentra
52     Sentra campaign 15    Near Market       Sentra
53      Sentra campaign 8    Near Market       Sentra
54     Sentra campaign 10    Near Market       Sentra
55     Sentra campaign 24    Near Market       Sentra
56     Sentra campaign 16    Near Market       Sentra
57     Sentra campaign 17    Near Market       Sentra

In [170]:
 df_table1.shape

(123699, 7)

In [172]:
df_table1[df_table1.duplicated()]

,Date,Data source,Campaign,Media Type,City,Metric,Value
80807,2021-03-29,Pinterest,shop at home,Display,Utica,Clicks,3.00
80858,2021-03-29,Pinterest,shop at home,Display,Utica,Clicks,3.00
80907,2021-03-29,Pinterest,shop at home,Display,Utica,Impressions,750.00
80908,2021-03-29,Pinterest,shop at home,Display,Utica,Media Cost,5.33
80909,2021-03-29,Pinterest,shop at home,Display,Utica,Clicks,3.00
...,...,...,...,...,...,...,...
122584,2021-09-27,Pinterest,shop at home,Display,Miami-Ft. Lauderdale,Media Cost,0.00
122585,2021-09-27,Pinterest,shop at home,Display,Miami-Ft. Lauderdale,Clicks,0.00
122586,2021-09-27,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Impressions,2.00
122587,2021-09-27,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Media Cost,0.00
122588,2021-09-27,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Clicks,0.00

In [174]:
df_table1.drop_duplicates(inplace=True)

In [176]:
df_table1.shape

(122629, 7)

In [178]:
df_table2.shape

(58, 3)

In [180]:
df_table2[df_table2.duplicated()]

Empty DataFrame
Columns: [Campaign, Message type, Model]
Index: []

#1.	Find out the top 5 months in terms of impressions

In [234]:

df_table1['Date']=pd.to_datetime(df_table1['Date'])

In [184]:
df_table1

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [221]:
df_table1['Day']=df_table1['Date'].dt.day
df_table1['month']=df_table1['Date'].dt.month
df_table1['year']=df_table1['Date'].dt.year
df_table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021

In [209]:
df1_table1 = df_table1[df_table1['Metric'] == 'Impressions']

In [211]:
df1_table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123684,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021
123687,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021
123690,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021

In [213]:
df2_table1 = df1_table1.groupby('Metric')['month'].value_counts()

In [215]:
df2_table1

Metric       month
Impressions  9        6929
             3        5784
             10       5719
             8        5651
             1        3119
             12       2877
             2        2631
             11       2330
             7        2134
             4        1706
             6        1168
             5         851
Name: count, dtype: int64

In [217]:
df2_table1.head()

Metric       month
Impressions  9        6929
             3        5784
             10       5719
             8        5651
             1        3119
Name: count, dtype: int64

#2.	Which model has maximum impressions?

In [238]:

dfmerge_table=pd.merge(df_table1,df_table2,on ='Campaign')
dfmerge_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [243]:
df3_table=dfmerge_table[dfmerge_table['Metric']=='Impressions']
df3_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019,Near Market,Kicks
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122614,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021,Near Market,Pathfinder
122617,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021,Near Market,Pathfinder
122620,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021,Near Market,Pathfinder
122623,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021,Near Market,Pathfinder

In [245]:
df3_table.groupby('Metric')['Model'].value_counts()

Metric       Model
Impressions  Pathfinder     9554
             Armada         7342
             Rogue          7281
             Altima         7206
             Kicks          4766
             Sentra         4012
             Multi-Model     738
Name: count, dtype: int64

In [247]:
df3_table.groupby('Metric')['Model'].value_counts().head(2)

Metric       Model
Impressions  Pathfinder    9554
             Armada        7342
Name: count, dtype: int64

3.	Find out the top 3 campaigns in terms of impressions for every message type

In [252]:
dfmerge1_table=pd.merge(df_table1,df_table2 , on = 'Campaign')
dfmerge1_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [270]:
df4_table = dfmerge1_table[dfmerge1_table['Metric']=='Impressions']
df4_table

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019,Near Market,Kicks
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122614,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021,Near Market,Pathfinder
122617,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021,Near Market,Pathfinder
122620,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021,Near Market,Pathfinder
122623,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021,Near Market,Pathfinder

In [277]:
df5_table1 = df4_table.groupby(['Message type','Metric'])['Campaign'].value_counts()
df5_table1

Message type   Metric       Campaign
Future Market  Impressions  Rogue campaign 4         2010
                            Altima campaign 3        1828
                            Rogue campaign 2         1641
                            Rogue campaign 5         1520
                            Sentra campaign 3        1403
                            Kicks campaign 4         1395
                            Sentra campaign 1        1318
                            Kicks campaign 3         1295
                            Altima campaign 2        1280
                            Rogue campaign 1         1000
                            Kicks campaign 6          837
                            Altima campaign 5         836
                            Altima campaign 1         818
                            shop at home              738
                            Kicks campaign 5          706
                            Rogue pre launch          648
                            Rogue campaign 3          462
                            Altima campaign 4         332
                            Altima campaign 6         303
                            Sentra campaign 4         152
                            Sentra campaign 2         143
Near Market    Impressions  Armada campaign 2        4464
                            Pathfinder campaign 2    1890
                            Armada campaign 4        1800
                            Pathfinder campaign 7    1444
                            Pathfinder campaign 8    1434
                            Pathfinder campaign 5    1418
                            Pathfinder campaign 6    1418
                            Altima campaign 8         997
                            Armada campaign 3         842
                            Pathfinder campaign 1     840
                            Altima campaign 7         812
                            Pathfinder campaign 4     630
                            Pathfinder campaign 3     480
                            Kicks campaign 1          276
                            Kicks campaign 2          257
                            Armada campaign 1         236
                            Sentra campaign 11         59
                            Sentra campaign 14         59
                            Sentra campaign 17         58
                            Sentra campaign 7          57
                            Sentra campaign 20         56
                            Sentra campaign 15         55
                            Sentra campaign 22         55
                            Sentra campaign 18         53
                            Sentra campaign 21         53
                            Sentra campaign 9          52
                            Sentra campaign 19         51
                            Sentra campaign 12         50
                            Sentra campaign 13         46
                            Sentra campaign 23         46
                            Sentra campaign 24         44
                            Sentra campaign 6          44
                            Sentra campaign 8          42
                            Sentra campaign 16         38
                            Sentra campaign 5          33
                            Sentra campaign 25         26
                            Sentra campaign 10         19
Name: count, dtype: int64

In [281]:
df5_table1.groupby(['Message type']).head(4)

Message type   Metric       Campaign
Future Market  Impressions  Rogue campaign 4         2010
                            Altima campaign 3        1828
                            Rogue campaign 2         1641
                            Rogue campaign 5         1520
Near Market    Impressions  Armada campaign 2        4464
                            Pathfinder campaign 2    1890
                            Armada campaign 4        1800
                            Pathfinder campaign 7    1444
Name: count, dtype: int64

4.	Does the campaign with maximum impressions also have maximum clicks?

In [294]:
df6_table1=df_table1[df_table1['Metric'].isin(['Impressions','Clicks'])]
df6_table1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,month,year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
5,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Clicks,0.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123692,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Clicks,102.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.0,30,9,2021

In [296]:
df7_table1=df6_table1.groupby('Metric')['Campaign'].value_counts()
df7_table1

Metric       Campaign
Clicks       Armada campaign 2        4464
             Rogue campaign 4         2010
             Pathfinder campaign 2    1890
             Altima campaign 3        1828
             Armada campaign 4        1800
                                      ...
Impressions  Sentra campaign 8          42
             Sentra campaign 16         38
             Sentra campaign 5          33
             Sentra campaign 25         26
             Sentra campaign 10         19
Name: count, Length: 116, dtype: int64